-- Reviews for seller profiles.

CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  reviewer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT NOT NULL CHECK (length(trim(comment)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reviews_no_self_review'
      AND conrelid = 'public.reviews'::regclass
  ) THEN
    ALTER TABLE public.reviews
      ADD CONSTRAINT reviews_no_self_review CHECK (seller_id <> reviewer_id);
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS reviews_seller_id_created_at_idx
  ON public.reviews (seller_id, created_at DESC);

DROP POLICY IF EXISTS "Todos pueden leer reviews" ON public.reviews;
CREATE POLICY "Todos pueden leer reviews" ON public.reviews
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Usuarios crean sus reviews" ON public.reviews;
CREATE POLICY "Usuarios crean sus reviews" ON public.reviews
  FOR INSERT WITH CHECK (
    auth.uid() = reviewer_id
    AND auth.uid() <> seller_id
  );

DROP POLICY IF EXISTS "Usuarios eliminan sus reviews" ON public.reviews;
CREATE POLICY "Usuarios eliminan sus reviews" ON public.reviews
  FOR DELETE USING (auth.uid() = reviewer_id);

DROP POLICY IF EXISTS "Admins eliminan reviews" ON public.reviews;
CREATE POLICY "Admins eliminan reviews" ON public.reviews
  FOR DELETE USING (
    auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin')
  );
